version: 0.0
os: linux

files:
  - source: /
    destination: /var/www
    overwrite: yes

permissions:
  - object: /var/www
    pattern: "**"
    owner: apache
    group: apache
    mode: 755
    type:
      - directory
  - object: /var/www
    pattern: "**"
    owner: apache
    group: apache
    mode: 644
    type:
      - file
  - object: /var/www/storage
    pattern: "**"
    owner: apache
    group: apache
    mode: 775
    type:
      - directory
  - object: /var/www/bootstrap/cache
    pattern: "**"
    owner: apache
    group: apache
    mode: 775
    type:
      - directory

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 600
      runas: root
    - location: stop_server.sh
      timeout: 60
      runas: root
  
  AfterInstall:
    - location: configure_environment.sh
      timeout: 300
      runas: root
    - location: setup_database.sh
      timeout: 600
      runas: root
    - location: set_permissions.sh
      timeout: 120
      runas: root
  
  ApplicationStart:
    - location: start_server.sh
      timeout: 120
      runas: root
  
  ApplicationStop:
    - location: stop_server.sh
      timeout: 60
      runas: root
  
  ValidateService:
    - location: validate_service.sh
      timeout: 60
      runas: root
