version: 0.0
os: linux

files:
  - source: /
    destination: /var/www
    overwrite: yes

permissions:
  - object: /var/www
    pattern: "**"
    owner: apache
    group: apache
    mode: 755
    type:
      - directory
  - object: /var/www
    pattern: "**"
    owner: apache
    group: apache
    mode: 644
    type:
      - file
  - object: /var/www/storage
    owner: apache
    group: apache
    mode: 775
    type:
      - directory
  - object: /var/www/bootstrap/cache
    owner: apache
    group: apache
    mode: 775
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 600
      runas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root
  
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
  
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root
