version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 20
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Installing system dependencies...
      - dnf update -y
      - dnf install -y git unzip

  pre_build:
    commands:
      - echo Installing Composer...
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - php -r "unlink('composer-setup.php');"
      - echo Installing PHP dependencies...
      - composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      - echo Installing Node.js dependencies including dev dependencies for build...
      - npm install
      - echo Checking if Laravel Mix is available...
      - npx mix --version || echo "Mix version check failed, but continuing..."
      - echo Building frontend assets...
      - npm run production

  build:
    commands:
      - echo Build phase started on `date`
      - echo Creating deployment artifact...
      - echo Removing development files and dependencies...
      - rm -rf node_modules
      - rm -rf tests
      - rm -f phpunit.xml
      - rm -f README.md
      - rm -f package*.json
      - rm -f webpack.mix.js
      - echo Verifying compiled assets exist...
      - ls -la public/css/ || echo "No CSS assets found"
      - ls -la public/js/ || echo "No JS assets found"
      - echo Creating optimized autoloader...
      - composer dump-autoload --optimize --no-dev
      - echo Clearing Laravel caches...
      - php artisan config:clear || true
      - php artisan route:clear || true
      - php artisan view:clear || true
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Creating archive for deployment...
      - echo "=== COMPREHENSIVE ARTIFACT VERIFICATION ==="
      - echo "Current directory: $(pwd)"
      - echo "Total files in build directory: $(find . -type f | wc -l)"
      - echo "Total directories: $(find . -type d | wc -l)"
      - echo ""
      - echo "Directory structure being packaged:"
      - find . -type d -name scripts -ls || echo "No scripts directory found"
      - ls -la scripts/ || echo "No scripts directory accessible"
      - echo ""
      - echo "Critical Laravel files check:"
      - echo "- artisan: $([ -f ./artisan ] && echo "✓ Present" || echo "✗ Missing")"
      - echo "- app directory: $([ -d ./app ] && echo "✓ Present" || echo "✗ Missing")"
      - echo "- config directory: $([ -d ./config ] && echo "✓ Present" || echo "✗ Missing")"
      - echo "- public directory: $([ -d ./public ] && echo "✓ Present" || echo "✗ Missing")"
      - echo "- composer.json: $([ -f ./composer.json ] && echo "✓ Present" || echo "✗ Missing")"
      - echo ""
      - echo "Top-level directory contents:"
      - ls -la . | head -20
      - echo ""
      - echo "Shell scripts in artifact:"
      - find . -name "*.sh" -ls || echo "No shell scripts found"
      - echo ""
      - echo "First 50 files that will be packaged:"
      - find . -type f | head -50
      - echo ""
      - echo "Checking .gitignore exclusions:"
      - [ -f .gitignore ] && echo "=== .gitignore contents ===" && cat .gitignore || echo "No .gitignore file"

artifacts:
  files:
    - '**/*'
  name: laravel-app-$(date +%Y-%m-%d-%H-%M-%S)
  base-directory: .

cache:
  paths:
    - '/root/.composer/cache/**/*'
    - '/root/.npm/**/*'
