version: 0.2

env:
  variables:
    # These will be set in CodeBuild Environment Variables
    # BROADCAST_DRIVER: "reverb" 
    # REVERB_APP_KEY: from CodeBuild
    # REVERB_APP_SECRET: from CodeBuild  
    # REVERB_APP_ID: from CodeBuild
    # REVERB_HOST: from CodeBuild
    # REVERB_PORT: from CodeBuild
    # REVERB_SCHEME: from CodeBuild
    # VITE_REVERB_APP_KEY: from CodeBuild
    # VITE_REVERB_HOST: from CodeBuild
    # VITE_REVERB_PORT: from CodeBuild  
    # VITE_REVERB_SCHEME: from CodeBuild
    
    # Legacy Pusher variables (not used but kept for compatibility)
    PUSHER_APP_KEY: "dummy_key"
    PUSHER_APP_SECRET: "dummy_secret"
    PUSHER_APP_ID: "dummy_id"
    PUSHER_APP_CLUSTER: "mt1"

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 20
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
      - echo Installing system dependencies...
      - dnf update -y
      - dnf install -y git unzip

  pre_build:
    commands:
      - echo Installing Composer...
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - php -r "unlink('composer-setup.php');"
      - echo Installing PHP dependencies...
      - composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      - echo Installing Node.js dependencies including dev dependencies for build...
      - npm install
      - echo Checking if Laravel Mix is available...
      - npx mix --version || echo "Mix version check failed, but continuing..."
      - echo Building frontend assets...
      - npm run production

  build:
    commands:
      - echo Build phase started on `date`
      - echo Creating deployment artifact...
      - echo Verifying compiled assets exist...
      - ls -la public/css/ || echo "No CSS assets found"
      - ls -la public/js/ || echo "No JS assets found"
      - echo Removing development files and dependencies...
      - rm -rf node_modules
      - rm -rf tests
      - rm -f phpunit.xml
      - rm -f README.md
      - rm -f package*.json
      - rm -f webpack.mix.js
      - echo Creating optimized autoloader...
      - composer dump-autoload --optimize --no-dev
      - echo Clearing Laravel caches...
      - php artisan config:clear || true
      - php artisan route:clear || true
      - php artisan view:clear || true
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Creating archive for deployment...
      - echo === COMPREHENSIVE ARTIFACT VERIFICATION ===
      - echo ""
      - echo "Directory structure being packaged:"
      - find . -type d -name scripts -ls || echo "No scripts directory found"
      - ls -la scripts/ || echo "No scripts directory accessible"
      - echo ""
      - echo "Critical Laravel files check:"
      - echo "- artisan:" $([ -f ./artisan ] && echo "✓ Present" || echo "✗ Missing")
      - echo "- app directory:" $([ -d ./app ] && echo "✓ Present" || echo "✗ Missing")
      - echo "- config directory:" $([ -d ./config ] && echo "✓ Present" || echo "✗ Missing")
      - echo "- public directory:" $([ -d ./public ] && echo "✓ Present" || echo "✗ Missing")
      - echo "- composer.json:" $([ -f ./composer.json ] && echo "✓ Present" || echo "✗ Missing")
      - echo ""
      - echo "Top-level directory contents:"
      - ls -la . | head -20
      - echo ""
      - echo "Shell scripts in artifact:"
      - find . -name "*.sh" -ls || echo "No shell scripts found"
      - echo ""
      - echo "First 50 files that will be packaged:"
      - find . -type f | head -50
      - echo ""
      - echo "Checking .gitignore exclusions:"
      - if [ -f .gitignore ]; then echo "=== .gitignore contents ==="; cat .gitignore; else echo "No .gitignore file"; fi

artifacts:
  files:
    - '**/*'
  name: laravel-app-$(date +%Y-%m-%d-%H-%M-%S)
  base-directory: .

cache:
  paths:
    - '/root/.composer/cache/**/*'
    - '/root/.npm/**/*'
